---
name: 'build images'

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sanitize repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return 'ghcr.io/${{ github.repository }}'.toLowerCase()

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          tags: 
            ${{ steps.repo_slug.outputs.result }}:${{ steps.get_version.outputs.VERSION }}
      
      - name: Deploy
        run: |
          echo $PWD
          python deploy/deploy.py
        env:
          VERSION_TAG: ${{ steps.get_version.outputs.VERSION }}
          PORTAINER_USER: ${{ secrets.PORTAINER_USER }} 
          PORTAINER_PASSW: ${{ secrets.PORTAINER_PASSW }} 
          PORTAINER_STACK_ID: ${{ secrets.PORTAINER_STACK_ID }}
          TIMER_BOT_KEY: ${{ secrets.TIMER_BOT_KEY }}